name: Azure Container Registry

on: [workflow_dispatch]

jobs:
  create-nginx-image:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get the source code from the repository
      uses: actions/checkout@v4

    - name: Build nginx image
      run: docker build -t atlasregistry79352.azurecr.io/my-nginx:latest .

    - name: List images created
      run: docker images

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v2
      with:
        #login-server: atlasregistry79352.azurecr.io
        login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
        #username: atlasregistry79352
        username: ${{ secrets.ACR_USERNAME }}
        #password: fwA8NFX+Y2S8tHJk+CMOyVanUZxffQG+w3Oy94RgIY+ACRCWxOjv
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Push image to Azure Container Registry  
      run: docker push atlasregistry79352.azurecr.io/my-nginx:latest
