name: Custom Nginx Docker Build

on: [workflow_dispatch]

jobs:
  create-nginx-image:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello World
      run: echo "Hello world!"

    - name: Get the source code from the repository
      uses: actions/checkout@v4

    - name: Build nginx image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-nginx:latest .

    - name: List images created
      run: docker images

    - name: Push image to Dockerhub
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PERSONAL_ACCESS_TOKEN }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-nginx:latest
