name: Azure Container Registry

on: [workflow_dispatch]

jobs:
  create-nginx-image:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get the source code from the repository
      uses: actions/checkout@v4

    - name: Build nginx image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-nginx:latest .

    - name: List images created
      run: docker images
      
    - name: Test with curl
      run: curl http://localhost:8080

    - name: Push image to Azure Container Registry
      uses: azure/docker-login@v2
      with:
        login-server: atlasregistry79352.azurecr.io
        username: ''
        password: ''
        
        run: docker push atlasregistry79352.azurecr.io/my-nginx:latest
